// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qualifica.Models;

namespace Qualifica.Migrations
{
    [DbContext(typeof(QualificaContext))]
    partial class QualificaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Qualifica.Models.Alocacao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Inicio");

                    b.Property<int?>("Postoid");

                    b.Property<DateTime?>("Termino");

                    b.Property<int>("idPosto");

                    b.Property<int>("idUsuario");

                    b.HasKey("id");

                    b.HasIndex("Postoid");

                    b.ToTable("Alocacao");
                });

            modelBuilder.Entity("Qualifica.Models.Especialidade", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("id");

                    b.ToTable("Especialidade");
                });

            modelBuilder.Entity("Qualifica.Models.Obra", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Endereco");

                    b.Property<DateTime>("Inicio");

                    b.Property<DateTime?>("Termino");

                    b.Property<int>("idProprietario");

                    b.HasKey("id");

                    b.ToTable("Obra");
                });

            modelBuilder.Entity("Qualifica.Models.Posto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.Property<int?>("Obraid");

                    b.Property<int>("Quantidade");

                    b.Property<int>("idEspecialidade");

                    b.HasKey("id");

                    b.HasIndex("Obraid");

                    b.ToTable("Posto");
                });

            modelBuilder.Entity("Qualifica.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CPF");

                    b.Property<string>("Login");

                    b.Property<string>("Nome");

                    b.Property<string>("RG");

                    b.Property<string>("Senha");

                    b.Property<byte>("Tipo");

                    b.HasKey("id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Qualifica.Models.Alocacao", b =>
                {
                    b.HasOne("Qualifica.Models.Posto")
                        .WithMany("Alocacoes")
                        .HasForeignKey("Postoid");
                });

            modelBuilder.Entity("Qualifica.Models.Posto", b =>
                {
                    b.HasOne("Qualifica.Models.Obra")
                        .WithMany("Posto")
                        .HasForeignKey("Obraid");
                });
#pragma warning restore 612, 618
        }
    }
}
