// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qualifica.API.Models;

namespace Qualifica.API.Migrations
{
    [DbContext(typeof(QualificaAPIContext))]
    partial class QualificaAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Qualifica.API.Models.Alocacao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Inicio");

                    b.Property<DateTime?>("Termino");

                    b.Property<int>("idPosto");

                    b.Property<int>("idTrabalhador");

                    b.HasKey("id");

                    b.ToTable("Alocacao");
                });

            modelBuilder.Entity("Qualifica.API.Models.Conquista", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Experiencia");

                    b.Property<string>("Imagem");

                    b.Property<string>("Nome");

                    b.Property<int?>("idCurso");

                    b.HasKey("id");

                    b.ToTable("Conquista");
                });

            modelBuilder.Entity("Qualifica.API.Models.ConquistaTrabalhador", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data");

                    b.Property<int>("idConquista");

                    b.Property<int>("idTrabalhador");

                    b.HasKey("id");

                    b.ToTable("ConquistaTrabalhador");
                });

            modelBuilder.Entity("Qualifica.API.Models.Construtora", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CNPJ");

                    b.Property<string>("Nome");

                    b.HasKey("id");

                    b.ToTable("Construtora");
                });

            modelBuilder.Entity("Qualifica.API.Models.Curso", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.Property<string>("Url");

                    b.HasKey("id");

                    b.ToTable("Curso");
                });

            modelBuilder.Entity("Qualifica.API.Models.Especialidade", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.HasKey("id");

                    b.ToTable("Especialidade");
                });

            modelBuilder.Entity("Qualifica.API.Models.EspecialidadeTrabalhador", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("idEspecialidade");

                    b.Property<int>("idTrabalhador");

                    b.HasKey("id");

                    b.ToTable("EspecialidadeTrabalhador");
                });

            modelBuilder.Entity("Qualifica.API.Models.GerenteObra", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF");

                    b.Property<string>("Nome");

                    b.Property<string>("RG");

                    b.Property<int>("idConstrutora");

                    b.Property<int?>("idGerente");

                    b.HasKey("id");

                    b.ToTable("GerenteObra");
                });

            modelBuilder.Entity("Qualifica.API.Models.Obra", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Endereco");

                    b.Property<DateTime>("Inicio");

                    b.Property<DateTime?>("Termino");

                    b.Property<int>("idConstrutora");

                    b.Property<int?>("idGerente");

                    b.HasKey("id");

                    b.ToTable("Obra");
                });

            modelBuilder.Entity("Qualifica.API.Models.Posto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.Property<int>("Quantidade");

                    b.Property<int>("idEspecialidade");

                    b.Property<int>("idObra");

                    b.HasKey("id");

                    b.ToTable("Posto");
                });

            modelBuilder.Entity("Qualifica.API.Models.Trabalhador", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF");

                    b.Property<DateTime>("Nascimento");

                    b.Property<string>("Nome");

                    b.Property<string>("RG");

                    b.HasKey("id");

                    b.ToTable("Trabalhador");
                });

            modelBuilder.Entity("Qualifica.API.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Login");

                    b.Property<string>("Senha");

                    b.Property<int?>("idGerente");

                    b.Property<int?>("idTrabalhador");

                    b.HasKey("id");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
